FROM debian

ARG G_ACCOUNT

ENV \
DEBIAN_FRONTEND=noninteractive \
LANG=C.UTF-8 \
ENV=/etc/profile \
USER=root 

WORKDIR /

RUN set -x && apt update \
  && mkdir -p /root/.local/bin && mkdir -p /root/.ghcup/bin \
  && apt install -y curl wget gnupg apt-utils git udev \
  && wget https://raw.githubusercontent.com/${G_ACCOUNT}/guild-operators/master/scripts/cnode-helper-scripts/guild-deploy.sh \
  && export SUDO='N' \
  && export UPDATE_CHECK='N' \
  && export BOOTSTRAP_HASKELL_NO_UPGRADE=1 \
  && chmod +x ./guild-deploy.sh &&  ./guild-deploy.sh -s pbcowx \
  && apt-get -y purge && apt-get -y clean && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*