{
 "title": "Guild Operator's monitoring",
 "description": "Stake Pool Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    { "expr": "(memused / memtotal)* 100", "legendFormat": "MemUtil" }
   ]
  },
  {
   "title": "Tipp diff (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "dbsynctipref", "legendFormat": "diff" }
   ]
  },
  {
   "title": "Tipp diff (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "nodetipref", "legendFormat": "diff" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    { "expr": "cpuutil", "legendFormat": "CPUUtil" }
   ]
  },
  {
   "title": "Block height (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "dbsyncBlockHeight", "legendFormat": "BlockHeight" }
   ]
  },
  {
   "title": "Block height (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "nodeBlockHeight", "legendFormat": "BlockHeight" }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Load" }
   ],
   "targets": [
    { "expr": "(load1m/100)", "legendFormat": "Load 1m" }
   ]
  },
  {
   "title": "Queue Length (dbsync)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "dbsyncQueueLength", "legendFormat": "QueueLength" }
   ]
  },
  {
   "title": "Uptime (node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "uptime", "legendFormat": "uptime" }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "Node"
    }
   ]
  }
 ]
}