FROM debian

ENV \
CNODE_HOME=/opt/cardano/cnode \
DEBIAN_FRONTEND=noninteractive \
LANG=C.UTF-8 \
ENV=/etc/profile \
USER=root \
PATH=$CNODE_HOME/scripts:/root/.cabal/bin:/root/.ghcup/bin:$PATH

WORKDIR /

RUN set -x && apt update \
  && mkdir -p /root/.cabal/bin && mkdir -p /root/.ghcup/bin \
  && apt install -y apt-utils wget gnupg git\
  && wget https://raw.githubusercontent.com/cardano-community/guild-operators/alpha/scripts/cnode-helper-scripts/prereqs.sh \
  && export SUDO='N' \
  && export UPDATE_CHECK='N' \
  && export BOOTSTRAP_HASKELL_NO_UPGRADE=1 \
  && chmod +x ./prereqs.sh &&  ./prereqs.sh -f -b alpha \
  && apt-get -y purge && apt-get -y clean && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*