FROM debian

ENV \
CNODE_HOME=/opt/cardano/cnode \
DEBIAN_FRONTEND=noninteractive \
LANG=C.UTF-8 \
ENV=/etc/profile \
USER=root \
PATH=$CNODE_HOME/scripts:/root/.cabal/bin:/root/.ghcup/bin:$PATH

WORKDIR /

RUN set -x && apt update \
  && mkdir -p /root/.cabal/bin && mkdir -p /root/.ghcup/bin \
  && apt install -y apt-utils wget gnupg git\
  && wget https://raw.githubusercontent.com/cardano-community/guild-operators/alpha/scripts/cnode-helper-scripts/prereqs.sh \
  && cat prereqs.sh | sed "s/SUDO='Y';/SUDO='N';/g" | sed 's/libssl1.0-dev/libssl-dev/g' > /tmp/prereqs.sh \
  && export BOOTSTRAP_HASKELL_NO_UPGRADE=1 \
  && chmod +x /tmp/prereqs.sh &&  /tmp/prereqs.sh -f -b alpha \
  && apt-get -y purge && apt-get -y clean && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*