name: Docker Image CD Stage 3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: dockerfile Stage2 Download
      run: |
        curl -sLo Dockerstage3 https://github.com/cardano-community/guild-operators/blob/master/files/docker/node/dockerfile_stage3
    - name: Compiling new node software
      run: |      
        docker build . --file Dockerstage3 --compress --tag cardanocommunity/cardano-node:stage3
    - name: docker push
      run: |
        docker push cardanocommunity/cardano-node:stage3
        docker tag cardanocommunity/cardano-node:stage3 cardanocommunity/cardano-node:latest
        docker push cardanocommunity/cardano-node:latest