name: Docker Image CD Stage 3

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Compiling new node software suite
      run: |      
        DOCKER_BUILDKIT=1 docker build . --file files/docker/node/dockerfile_stage3 --compress --tag cardanocommunity/cardano-node:stage3
    - name: docker push stage3 and latest
      run: |
        CNVERSION=`cat files/docker/node/release-versions/cardano-node-latest.txt`
        docker tag cardanocommunity/cardano-node:stage3 cardanocommunity/cardano-node:latest
        docker tag cardanocommunity/cardano-node:stage3 cardanocommunity/cardano-node:$CNVERSION
        docker push cardanocommunity/cardano-node:latest
        docker push cardanocommunity/cardano-node:$CNVERSION
