name: Pre-merge Debian Cabal Build Tests

on:
  workflow_dispatch:

jobs:
  test-cabal-build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Examine GITHUB_REF
      run: |
        echo "pr_branch ${{ steps.pr_branch.outputs.branch }}"
    - name: Testing cabal-build-all.sh
      run: |
        docker build . --file files/tests/pre-merge/debian-cabal.containerfile --compress --build-arg BRANCH=${{ steps.pr_branch.outputs.branch }}  --tag ghcr.io/cardano-community/pre-merge:debian_cabal
  test-cabal-build-all-with-system-libsodium:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Examine GITHUB_REF
      run: |
        echo "pr_branch ${{ steps.pr_branch.outputs.branch }}"
    - name: Testing cabal-build-all.sh -l
      run: |
        docker build . --file files/tests/pre-merge/debian-cabal_-l.containerfile --compress --build-arg BRANCH=${{ steps.pr_branch.outputs.branch }}  --tag ghcr.io/cardano-community/pre-merge:debian_cabal_-l
