name: Pre-merge RockyLinux8

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/prereqs.sh
      - scripts/cnode-helper-scripts/cabal-build-all.sh
      - files/cabal.project.local
      - files/tests/rockylinux8_prereqs.sh.containerfile
      - files/tests/rockylinux8_prereqs.sh_-l.containerfile

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Testing prereqs.sh
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file files/tests/pre-merge/rockylinux8_prereqs.sh.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-rockylinux8:prereqs_${COMMIT}
    - name: Push pre-merge-rockylinux8:prereqs_${COMMIT}
      run: |
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker push ghcr.io/cardano-community/pre-merge-rockylinux8:prereqs_${COMMIT}

  prerequisites-with-system-libsodium:
    runs-on: ubuntu-latest
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Testing prereqs.sh -l
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file files/tests/pre-merge/rockylinux8_prereqs.sh_-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-rockylinux8:prereqs_-l_${COMMIT}
    - name: Push pre-merge-rockylinux8:prereqs_-l_${COMMIT}
      run: |
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        docker push ghcr.io/cardano-community/pre-merge-rockylinux8:prereqs_-l_${COMMIT}

  build:
    needs: prerequisites
    runs-on: ubuntu-latest
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Testing cabal-build-all.sh
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        echo "Working from PR Branch ${BRANCH} on Commit ${COMMIT}"
        docker build . --file files/tests/pre-merge/rockylinux8-cabal.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-rockylinux8:cabal_${COMMIT}

  build-with-system-libsodium:
    needs: prerequisites-with-system-libsodium
    runs-on: ubuntu-latest
    steps:
    - name: Provide additional free space
      run: |
        # Workaround to provide additional free space for builds.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Extract branch from PR
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF}"
      id: pr_branch
    - name: Testing cabal-build-all.sh -l
      run: |
        export BRANCH=${{ steps.pr_branch.outputs.branch }}
        export COMMIT=$(git rev-parse --short "$GITHUB_SHA")
        echo "Working from PR Branch ${BRANCH} on Commit ${COMMIT}"
        docker build . --file files/tests/pre-merge/rockylinux8-cabal_-l.containerfile --compress --build-arg BRANCH --build-arg COMMIT --tag ghcr.io/cardano-community/pre-merge-rockylinux8:cabal_-l_${COMMIT}
