name: Pre-merge AmazonLinux2 Prerequisites w/ system libsodium

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/prereqs.sh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Testing prereqs.sh -l
      run: |
        docker build . --file files/tests/pre-merge/amazonlinux2_prereqs.sh_-l.containerfile --compress --tag chaincrucial/pre-merge:amazonlinux2_prereqs.sh