name: Pre-merge Ubuntu20 Cabal Build w/ system libsodium

on:
  workflow_dispatch:
  pull_request:
    paths:
      - scripts/cnode-helper-scripts/cabal-build-all.sh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Testing prereqs.sh -l and cabal-build-all.sh -l
      run: |
        docker build . --file files/tests/pre-merge/ubuntu20-cabal_-l.containerfile --compress --tag chaincrucial/pre-merge:ubuntu20_cabal
